name: huekeys
description: Control the keyboard backlight on System76 laptops
full_description: >
  Huekeys is a fun application that makes it easy to adjust your System76
  keyboard colors and brightness. In addition to the simple ability to set and
  get the color and brightness, it also provides several patterns that you can
  run indefinitely, to really make your keyboard pop!
