name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - run: sudo apt-get -qy install --no-install-recommends gcc libgtk-3-dev libayatana-appindicator3-dev

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - uses: actions/checkout@v3

      - run: make

      - id: app
        run: echo '::set-output name=name::'$(make appname)

      - name: test
        run: |
          echo 'ref: ${{ github.ref }}'
          echo 'name: ${{ steps.app.outputs.name }}'
          echo 'version: '$(make version)

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.app.outputs.name }}
