name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - run: sudo apt-get -qy install --no-install-recommends gcc libgtk-3-dev libayatana-appindicator3-dev

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - uses: actions/checkout@v3

      - run: make
