name: build
on:
  push:
    branches: ["main"]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - run: sudo apt-get -qy install --no-install-recommends gcc libgtk-3-dev libayatana-appindicator3-dev

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - uses: actions/checkout@v3

      - run: make

      - id: app
        run: echo '::set-output name=name::'$(make appname)

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.app.outputs.name }}
        if: startsWith(github.ref, 'refs/tags/')

      - run: gh workflow run release -R BitPonyLLC/homebrew-tap
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_BRADRF_PAT }}
        if: startsWith(github.ref, 'refs/tags/')
