name: build
on:
  push:
    branches: ["main"]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    outputs:
      appname: ${{ steps.app.outputs.name }}

    steps:
      - run: >
          sudo apt-get -qy install --no-install-recommends
          gcc libgtk-3-dev libayatana-appindicator3-dev

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - run: make

      - id: app
        run: echo '::set-output name=name::'$(make appname)

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.app.outputs.name }}-${{ github.sha }}
          path: ${{ steps.app.outputs.name }}
          retention-days: 1

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.appname }}-${{ github.sha }}
          path: ${{ needs.build.outputs.appname }}

      - id: release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ needs.build.outputs.appname }}/*
          fail_on_unmatched_files: true

      - run: gh workflow run release -R BitPonyLLC/homebrew-tap
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_BRADRF_PAT }}

      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          nodetail: true
          title: "Released ${{ steps.release.outputs.url }}"
